[project]
name = "mcpserver"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.11.0",
    "minio>=7.2.0",
    "pymupdf>=1.26.3"
]

[tool.uv.workspace]
members = [
    "MCPServer",
]
